[lint]
ignore = [
    "DTZ005", "DTZ006", "DTZ007",
    "EM101", "EM102", "TRY003",
    "FBT001", "FBT002",
    "ANN", "D", "S",
    "T201",
    "UP006", "UP007", "UP035",
    "FA100", "SIM117",
    "BLE001", "PERF102", "RUF059", "LOG015",
    "F841", "F821",
]
